name: interior_design
description: A new Flutter project.
publish_to:
version: 1.0.0+1
environment:
  sdk: '>=2.19.0-74.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  bloc:
  flutter_rating_bar: ^4.0.1
  equatable:
  internet_connection_checker:
  shared_preferences:
  http:
  dartz:
  get_it:




  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

